# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MicroBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MicroBlog

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Purchases'

end
