# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
